biocore/qiime

qiime/workflow/pick_open_reference_otus.py
scripts/pick_open_reference_otus.py

Fixes the application of the --minimum_failure_threshold and creation of the subsampling failures file till after step2 begins. Fixes #1830

Fix issue #1830

---

tests/test_rarefaction.py

See details for this change in #1836.

TST: rarefaction tests no longer test depth of zero

---

qiime/workflow/pick_open_reference_otus.py
tests/test_rarefaction.py
tests/test_simsam.py
tests/test_workflow/test_pick_open_reference_otus.py

Fixes #1849. @gregcaporaso can you please review?

BUG: replace Table.from_hdf5 with biom.load_table

---

qiime/make_rarefaction_plots.py
tests/test_make_rarefaction_plots.py

DOC: fix make_rarefaction_plots.py message about rarefaction curve truncation

---

qiime/compare_categories.py
qiime/differential_abundance.py
qiime/extract_barcodes.py
qiime/filter.py
qiime/join_paired_ends.py
qiime/normalize_table.py
qiime/parse.py
qiime/quality_scores_plot.py
qiime/split_libraries_fastq.py
qiime/split_libraries_lea_seq.py
qiime/util.py
scripts/quality_scores_plot.py
tests/test_util.py

Fixes #1870 #1873 #1875 #1879.

BUG FIX PARTAY!!

---

ChangeLog.md

DOC: finish cleaning up changelog

---

doc/tutorials/fungal_its_analysis.rst
doc/tutorials/illumina_overview_tutorial.rst
examples/ipynb/Fungal-ITS-analysis.ipynb
examples/ipynb/illumina_overview_tutorial.ipynb

@gregcaporaso can you please review?
Addresses part of #1781.

DOC: update fungal ITS tutorial to work with 1.9.0

---

doc/tutorials/index.rst
doc/tutorials/open_reference_illumina_processing.rst
doc/tutorials/otu_picking.rst
doc/tutorials/processing_18S_data.rst
examples/ipynb/Fungal-ITS-analysis.ipynb

@gregcaporaso and I "pair-programmed" this.

DOC: update several tutorial

---

qiime/split_libraries_lea_seq.py
qiime_test_data/split_libraries_lea_seq/map.txt
scripts/split_libraries_lea_seq.py
tests/test_split_libraries_lea_seq.py

able to merge @jairideout! :-)
Thanks for pointing it out. (I didn't realise that I submitted the last pull request directly from my master branch. That had resulted in the merge conflict.)

Improvement in split_libraries_lea_seq.py

---

qiime/util.py
tests/test_util.py

BUG: better error message for missing required headers

---

ChangeLog.md
qiime/make_2d_plots.py
scripts/make_2d_plots.py

fixes #1884 
Uses the same interface and behaviour as emperor.
@ElDeveloper, would you be able to review this one?

make_2d_plots.py now handles relative proportions explained correctly

---

ChangeLog.md
qiime/plot_taxa_summary.py
scripts/plot_taxa_summary.py
tests/test_plot_taxa_summary.py

removed count column from plot_taxa_summary.py

---

scripts/make_otu_heatmap.py

fixes #1906
simplest bug fix ever.

fixed heatmap bug where observations were unnecessarily required

---

ChangeLog.md
qiime/assign_taxonomy.py
scripts/assign_taxonomy.py
scripts/parallel_assign_taxonomy_rdp.py
tests/test_assign_taxonomy.py

changed default confidence threshold for Naive Bayes classifiers

---

doc/install/install.rst

Add more prerequisite packages for Ubuntu; add note about the install
instructions possibly being incomplete depending on the user's
system/configuration; make non-sudo install section more apparent.
Fixes #1817 #1863.

DOC: install doc updates

---

home_static/dataFiles.html

WEB: add 1.9.0 AMI to resources page

---

scripts/collapse_samples.py

Added default to `collapse_samples.py` for the `--collapse_mode` option.

Added documentation to collapse_samples.py

---

scripts/plot_semivariogram.py

Also made a two character change in credits string that had authors not listed independently. Should resolve issue  #1956

Fixed xlim and ylim handling

---

ChangeLog.md
setup.py
tests/test_parallel/test_identify_chimeric_seqs.py

Updated to qiime-default-reference 0.1.2 and scikit-bio 0.2.3.
Fixes #1972.

BUG: update minimum required versions of two deps

---

ChangeLog.md
doc/install/install.rst
doc/tutorials/working_with_aws.rst
qiime/util.py
scripts/filter_otus_from_otu_table.py
scripts/filter_samples_from_otu_table.py
scripts/filter_taxa_from_otu_table.py
scripts/jackknifed_beta_diversity.py
scripts/split_libraries_fastq.py

a space odyssey (addressing multiple issues for 1.9.1)

---

ChangeLog.md
doc/install/qiime_config.rst
qiime/support_files/qiime_config
scripts/start_parallel_jobs_slurm.py

fixes #2017. 
This includes the commits in #2019, just adds a couple of related clean-ups.

added ability to pass runtime limit to start_parallel_jobs_slurm.py

---

ChangeLog.md
scripts/filter_samples_from_otu_table.py

manually confirmed that this works, that the script usage tests pass, and that the updated error check is hit when it should be.

fixes #2003

---

ChangeLog.md
scripts/start_parallel_jobs_slurm.py

@jairideout and I pair-programmed this. @johnchase ran into this issue on our cluster.

fix bug in start_parallel_jobs_slurm.py 

---

home_static/dataFiles.html

Will close #2105 
Still writing, do not merge!
Started by adding qiita links to Bokulich et al, 2013.
Three studies are still missing links to qiita. 
ONLY links to qiita have been added.

Add mock community data to dataFiles.html

---

doc/install/alternatives.rst
doc/install/index.rst
doc/install/install.rst

@tanaes and @gregcaporaso please comment. Then let's merge and get these instructions online.

New installation instructions using Conda

---

doc/install/alternative.rst
doc/install/index.rst
doc/install/install.rst

this was written in collaboration with @cuttlefishh.
replaces #2164, #2162

DOC: updates install instructions to use conda

---

scripts/filter_fasta.py

A simple improvement to filter_fasta doc to explain the format for valid_states.

improve doc for filter_fasta (--valid_states)

---

doc/install/alternative.rst

Based on @colinbrislawn's work in https://github.com/biocore/qiime/pull/2194

DOC/BUG: fix broken BLAST download links
